name: nfs-provisioner 
apiVersion: v2
version: 1.0
dependencies: # A list of the chart requirements (optional)
  - name: nfs-subdir-external-provisioner 
    version: 4.0.18
    repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

    
