---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awesome-production
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/babayaga-creator/oc.git
    targetRevision: main
    path: nfs-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  syncPolicy:
    automated: { }
    syncOptions:
    - CreateNamespace=true